# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2eaf4e356edcea12ce64c27d13b21b96592c4ac9809900a79fbe37538d91748b870d36eef4add8589080850c4127e5497e37b422ffead706048708202b73a39f

test:
  secret_key_base: ae4c7a4a8bd9176735a1b2832a3c9abe2709fca12a8b19d67a7ce9fced6084a5cb60d06d66c57f2529488aa5c6cf6c529442f0d8e16b1aa020544acbc7b645c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
